
DROP TYPE IF EXISTS roles;

CREATE TYPE roles AS ENUM (
  'Captain',
  'Reporter',
  'Member',
  'Guest'
);


CREATE TABLE IF NOT EXISTS members (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  player_id INTEGER REFERENCES trivia_players(id) NOT NULL,
  team_id INTEGER REFERENCES trivia_teams(id) NOT NULL,
  role roles NOT NULL
)