DROP TABLE IF EXISTS trivia_attendees;


CREATE TABLE IF NOT EXISTS trivia_attendees(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  team_id INTEGER REFERENCES trivia_teams(id) NOT NULL,
  player_id INTEGER REFERENCES trivia_players(id) NOT NULL,
  event_id INTEGER REFERENCES trivia_events(id) NOT NULL
)