DROP TABLE IF EXISTS trivia_players CASCADE;
DROP TABLE IF EXISTS trivia_teams CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS trivia_locations CASCADE;
DROP TABLE IF EXISTS trivia_events CASCADE;
DROP TABLE IF EXISTS trivia_results CASCADE;
DROP TYPE IF EXISTS options;
DROP TABLE IF EXISTS trivia_attendees CASCADE;
DROP TABLE IF EXISTS schemaversion;